### PR TITLE
Use full_name again.

### LINKED ISSUE #76: Electron configuration in DB_EN
Hi,

I have been working a bit with FAC lately and I find  that it would be very convenient to  be able to print the full electron configuration in the verbose ASCII level file (DB_EN). Eliminating all empty and full shells makes  it unnecessarily hard to reconstruct the actual electron configuration of each level (programmatically).

When I look at the file in person I manage to figure out what the distribution should be, but automating this is very difficult.

Is there a specific reason why they aren't printed fully? (after all they are somewhat accessible with the GetConfigNR() and ListConfig()) methods in pfac, but even with those lists it is hard to match them automatically, since different configurations get mapped onto the same identifier when dropping the open and full orbitals.)

Are you ware of any workaround, and do you think that this could be a convenience feature to add in the future?

Cheers and thanks for this very versatile code!

### PR DESCRIPTION
**Pull request by fujiisoup**
Closes #76 

Fix for the regression in #305

### CODE REVIEW

**Comment by mfgu** [comment]
please don't change this. always print full name leads to too long strings for very complex configurations. you have too options if you want the full name printed:
SetOption('structure:full_name', 1)

or do not use Closed()  function to define closed shells, shells defined in Config() function are always printed fully regardless of whether it's fully occupied or not.

**Comment by fujiisoup** [comment]
https://github.com/flexible-atomic-code/fac/blob/e447db18a9b65c859cddaaf4aaf754b4ad3e14fe/demo/structure/ref/ne.lev#L37-L40

For example in this file, 2s and 2p orbitals are not defined by Closed but not shown in the file.

**Comment by mfgu** [comment]
sorry, then you have to use SetOption('structure:full_name',1) to turn it
on. I changed the default to not print full name as it was causing more
complaints from others.

**Comment by fujiisoup** [comment]
I think it would be nice at least `sname` shows full (except for those defined by closed) configuration. 
I saw in some other results, `4f6` is regarded as "fully occupied" and then it is difficult to find whether 4p6 or 4f6 is fully occupied.

Probably `sname` does not become too long?

**Comment by fujiisoup** [comment]
OK. I checked the other result and found that 4f6 is omitted from `name` but not from `sname`. Probably then we can recover the names from `ncomplex` and `sname`.

**Pull request closed without merging**
