### PR TITLE
test for errornous crmodel

### PR DESCRIPTION
**Pull request by fujiisoup**
This adds a test which currently fac crashes with segfault if openmp is used.

### CODE REVIEW

**Comment by fujiisoup** [comment]
In travis, crmodel with openmp does not crash but the output result looks wrong.

**Comment by mfgu** [comment]
Hi Keisuke,
I think i have fixed the problem, and merged your new test setup.

**Comment by fujiisoup** [comment]
Thanks for your quick update, @mfgu.

But I think the tests are still failing with openmp.

**Comment by mfgu** [comment]
that has to do with the simple_crm.py script. the InitializeMPI function
exists in both fac and crm modules, so when both are imported in the global
name space, they clash with each other. you need to call the module
specific version separately. I fixed the script.

**Pull request merged**
